### ISSUE TITLE
D_INVOICES ETL Needs Work

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#10]

**Comment by harrisward** [comment]
D_INVOICES represents a single row per invoice. This dimension contains some basic details like Invoice Status, Invoice Number. Thee attributes are valid for a dimension. Im not sure if the various invoice dates are valid for this dimension. We don't normally join a date dimension to other dimensions (snowflaking). It might be that we need a new fact table at some point to represent the Invoices. In reality this fact table should be called F_INVOICE_MANAGEMENT (which already exists but it at a granularity of invoice line items). This fact table would contain one row per invoice with each date for that invoice. We would then create a new fact table to represent sales like F_SALES.

Lets investigate the approach for invoice dimensions in relation to sales

**Comment by fraserward** [comment]
Also to insert the Dimension rule of nulls values / not set and update Demo data with same.

**Comment by harrisward** [comment]
Fixed up D_INVOICES. Removed date fields and cleaned up the transformation. Had to also edit F_SALES ETL and various DEMO ETL to work with these changes. Tested on live data and demo data
