### ISSUE TITLE
Trim whitespace in Demo Data

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#115]
We need to make sure all string data has been trimmed in the ETl. For example, Product Category in D_PRODUCTS.

![image](https://user-images.githubusercontent.com/6827832/107093204-c6395e00-67fc-11eb-89e7-793f9f67fed4.png)

**Comment by fraserward** [comment]
Added trim strings to all demo dimension transformations that were missing this operation

**Comment by fraserward** [comment]
Tested by SA.
