### ISSUE TITLE
Remove duration from Demo Data Emails in Activities

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-data-integration#126]
Emails have duration values in the demo data and should be removed

**Comment by fraserward** [comment]
Check this issue

**Comment by fraserward** [comment]
This was done previously.  Tested ok.

**Comment by harrisward** [comment]
Tested using the following query:

SELECT
        DO.OPPORTUNITY_NAME,
        DA.ACTIVITY_TYPE,
        COUNT(FA.ACTIVITY_TK),
        SUM(FA.ACTIVITY_DURATION)
FROM F_ACTIVITIES FA
INNER JOIN D_ACTIVITIES DA
ON FA.ACTIVITY_TK = DA.ACTIVITY_TK
INNER JOIN D_OPPORTUNITIES DO
ON FA.ACTIVITY_PARENT_TK = DO.OPPORTUNITY_TK
WHERE DA.ACTIVITY_PARENT_TYPE = 'Opportunities'
AND DA.ACTIVITY_TYPE  = 'Email'
GROUP BY 1,2
