### ISSUE TITLE
Tasks (without date) not populating in Activities Report

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-data-integration#139]
Completed Tasks without set dates don't populate the activities report as one of the parameters for this report is date (month/year) select or 'All Dates'

Possible fix would be to set all tasks without a date to a particular number and having this as an Unset Date option in the parameter pull-down.

Discussions needed.

**Comment by harrisward** [comment]
Discussed 19th May:

The solution is to set the task date to the task created date if no original task date has been set. This will allow the tasks to be queries in analytics. When a task is updated with a NEW real task date then we will update the task date to match

**Comment by harrisward** [comment]
When the ACTIVITY_DATE_TK is NULL / 0 then we should use the date_entered from the source database instead.

**Comment by fraserward** [comment]
Updated ActivitiesFact transformation

Pull Request:  https://github.com/ivylabs/suitecrm-data-integration/pull/168

**Comment by harrisward** [comment]
Tested and merged

**Comment by johnM2401** [comment]
Hey @harrisward 

I've had a look, and it appears as though all Tasks are just taking the "Date Created" value, regardless of whether a "Due Date" is present

I have created these 3 Tasks today (24/06):
![image](https://user-images.githubusercontent.com/13675281/123257349-f488b300-d4e9-11eb-933f-8e541a37cbf1.png)

However, all of these show as Today (24/06) in Analytics;
![image](https://user-images.githubusercontent.com/13675281/123257247-d0c56d00-d4e9-11eb-80c5-d02e4ef80fe7.png)

**Comment by harrisward** [comment]
@johnM2401 From the requirements we use the date_start from the tasks table and NOT the date_due field. Can you retest the logic with date_start fields instead please? This should work

**Comment by johnM2401** [comment]
@harrisward 
Ahh, yep, you're totally right.
My bad, must have gotten it confused with something else.

Have given it a go with the Start Date and looks good.

Thanks for clarifying!
