### ISSUE TITLE
Create Lead Tracking Fact Table and ETL

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#14]

**Comment by samus-aran** [comment]
Tested this and the F_LEAD_TRACKING is not pulling anything in even though there is a large amount of data in staging tables.

![Screenshot_2020-03-09 localhost 9009 mariadb suitecrm_analytics_dwh_3 phpMyAdmin 4 8 5](https://user-images.githubusercontent.com/4041275/76207072-09f2a480-61f5-11ea-8fec-bdd047d40fcd.png)

**Comment by samus-aran** [comment]
Not alot to go on for the error log:

- 2020/03/09 10:56:03 - populateFacts - Starting entry [populateLeadTrackingFact]
- 2020/03/09 10:56:03 - populateLeadTrackingFact - Loading transformation from XML file [file:///var/www/html/suitecrm-data-integration-2/suitecrm-data-integration-server/solution/DWH/FACTS/populateLeadTrackingFact.ktr]
- 2020/03/09 10:56:03 - populateLeadTrackingFact - Using run configuration [Pentaho local]
- 2020/03/09 10:56:03 - populateLeadTrackingFact - Using legacy execution engine
- 2020/03/09 10:56:03 - populateLeadTrackingFact - Dispatching started for transformation [populateLeadTrackingFact]
- 2020/03/09 10:56:03 - F_LEAD_TRACKING - Open.0 - Finished reading query, closing connection.
- 2020/03/09 10:56:03 - S_LEADS.0 - Finished reading query, closing connection.
- 2020/03/09 10:56:03 - S_LEADS_AUDIT.0 - Finished reading query, closing connection.
- 2020/03/09 10:56:03 - S_LEADS Not NEW.0 - Finished reading query, closing connection.
- 2020/03/09 10:56:04 - populateFacts - Starting entry [populateOpportunityTrackingFact]
- 2020/03/09 10:56:04 - populateOpportunityTrackingFact - Loading transformation from XML file [file:///var/www/html/suitecrm-data-integration-2/suitecrm-data-integration-server/solution/DWH/FACTS/populateOpportunityTrackingFact.ktr]
- 2020/03/09 10:56:04 - populateOpportunityTrackingFact - Using run configuration [Pentaho local]
- 2020/03/09 10:56:04 - populateOpportunityTrackingFact - Using legacy execution engine
- 2020/03/09 10:56:04 - populateOpportunityTrackingFact - Dispatching started for transformation [populateOpportunityTrackingFact]
- 2020/03/09 10:56:04 - S_OPPORTUNITIES_AUDIT.0 - Finished reading query, closing connection.
- 2020/03/09 10:56:04 - Prepare Audit Fields.0 - Finished processing (I=0, O=0, R=1322, W=1322, U=0, E=0)
- 2020/03/09 10:56:04 - S_OPPORTUNITIES_AUDIT.0 - Finished processing (I=1322, O=0, R=0, W=1322, U=0, E=0)
- 2020/03/09 10:56:04 - F_OPPORTUNITY_TRACKING - Open.0 - Finished reading query, closing connection.
- 2020/03/09 10:56:04 - S_OPPORTUNITIES Not NEW.0 - Finished reading query, closing connection.
- 2020/03/09 10:56:04 - S_OPPORTUNITIES Not NEW.0 - Finished processing (I=129, O=0, R=0, W=129, U=0, E=0)
- 2020/03/09 10:56:04 - S_OPPORTUNITIES.0 - Finished reading query, closing connection.
- 2020/03/09 10:56:04 - S_OPPORTUNITIES.0 - Finished processing (I=1022, O=0, R=0, W=1022, U=0, E=0)
- 2020/03/09 10:56:04 - Lookup Existing New.0 - Finished processing (I=0, O=0, R=1022, W=1022, U=0, E=0)
- 2020/03/09 10:56:04 - Filter Existing New.0 - Finished processing (I=0, O=0, R=1022, W=1022, U=0, E=0)
- 2020/03/09 10:56:04 - Prepare Fields.0 - Finished processing (I=0, O=0, R=1022, W=1022, U=0, E=0)
- 2020/03/09 10:56:04 - Initial Union.0 - Finished processing (I=0, O=0, R=1151, W=1151, U=0, E=0)
- 2020/03/09 10:56:04 - Master Union.0 - Finished processing (I=0, O=0, R=2473, W=2473, U=0, E=0)
- 2020/03/09 10:56:04 - Lookup Opportunity TKs.0 - Finished processing (I=2473, O=0, R=2473, W=2473, U=0, E=0)
- 2020/03/09 10:56:04 - Order New Before Other.0 - Finished processing (I=0, O=0, R=2473, W=2473, U=0, E=0)
- 2020/03/09 10:56:04 - Calculate Cloned Rows.0 - Optimization level set to 9.
- 2020/03/09 10:56:04 - Sort by Opportunity ID & Date.0 - Finished processing (I=0, O=0, R=2473, W=2473, U=0, E=0)
- 2020/03/09 10:56:04 - Event Count.0 - Optimization level set to 9.
- 2020/03/09 10:56:04 - Get Event Opportunity & Lag Dates.0 - Finished processing (I=0, O=0, R=2473, W=2473, U=0, E=0)
- 2020/03/09 10:56:04 - Calculate Cloned Rows.0 - Finished processing (I=0, O=0, R=2473, W=2473, U=0, E=0)
- 2020/03/09 10:56:04 - Clone Rows.0 - Finished processing (I=0, O=0, R=2473, W=3924, U=0, E=0)
- 2020/03/09 10:56:04 - Event Count.0 - Finished processing (I=0, O=0, R=3924, W=3924, U=0, E=0)
- 2020/03/09 10:56:04 - FIlter Cloned Rows.0 - Finished processing (I=0, O=0, R=3924, W=3924, U=0, E=0)
- 2020/03/09 10:56:04 - Event Age = 0.0 - Finished processing (I=0, O=0, R=2473, W=2473, U=0, E=0)
- 2020/03/09 10:56:04 - Calculate Event Age.0 - Finished processing (I=0, O=0, R=1451, W=1451, U=0, E=0)
- 2020/03/09 10:56:04 - Remap Cloned Rows.0 - Finished processing (I=0, O=0, R=1451, W=1451, U=0, E=0)
- 2020/03/09 10:56:04 - Select Original Rows.0 - Finished processing (I=0, O=0, R=2473, W=2473, U=0, E=0)
- 2020/03/09 10:56:04 - Union Rows.0 - Finished processing (I=0, O=0, R=3924, W=3924, U=0, E=0)
- 2020/03/09 10:56:04 - Date TKs.0 - Optimization level set to 9.
- 2020/03/09 10:56:04 - Final Sort.0 - Finished processing (I=0, O=0, R=3924, W=3924, U=0, E=0)
- 2020/03/09 10:56:04 - Date TKs.0 - Finished processing (I=0, O=0, R=3924, W=3924, U=0, E=0)
- 2020/03/09 10:56:08 - F_OPPORTUNITY_TRACKING.0 - Finished processing (I=3924, O=3924, R=3924, W=3924, U=0, E=0)
- 2020/03/09 10:56:08 - populateFacts - Starting entry [Success]
- 2020/03/09 10:56:08 - populateFacts - Finished job entry [Success] (result=[true])
- 2020/03/09 10:56:08 - populateFacts - Finished job entry [populateOpportunityTrackingFact] (result=[true])
- 2020/03/09 10:56:08 - populateFacts - Finished job entry [populateLeadTrackingFact] (result=[true])
- 2020/03/09 10:56:08 - populateFacts - Finished job entry [populateInvoiceManagementFact] (result=[true])
- 2020/03/09 10:56:08 - populateFacts - Finished job entry [populateCaseManagementFact] (result=[true])
- 2020/03/09 10:56:08 - populateFacts - Finished job entry [populateOpportunityManagementFact] (result=[true])
- 2020/03/09 10:56:08 - populateFacts - Finished job entry [populateLeadManagementFact] (result=[true])
- 2020/03/09 10:56:08 - populateFacts - Finished job entry [Populating Facts] (result=[true])
- 2020/03/09 10:56:08 - populateDataWarehouse - Starting entry [populateCustomDimensions]
- 2020/03/09 10:56:08 - populateCustomDimensions - Using run configuration [Pentaho local]
- 2020/03/09 10:56:08 - populateCustomDimensions - Starting entry [Populating Custom Dimensions]
-

**Comment by samus-aran** [comment]
Trying to process the query in F_LEAD_TRACKING 

```
SELECT
  id
, parent_id
, date_created
, created_by
, field_name
, data_type
, before_value_string
, after_value_string
, before_value_text
, after_value_text
FROM S_LEADS_AUDIT
WHERE field_name = 'status'
AND (parent_id = '${LEAD_ID}' OR 1 = '${LEAD_ID}')
```

I'm not understanding the parent_id but I'm assuming that is to ensure it has a link to a LEAD. That doesn't seem to successfully return in my script. The Opportunities Audit SQL excludes this part in the SQL.

**Comment by samus-aran** [comment]
I updated both the transformations:
- populateLeadTrackingFact > S_LEADS_AUDIT
- populateLeadTrackingFact > S_LEADS Not NEW

to exclude the:

AND (parent_id = '${LEAD_ID}' OR 1 = '${LEAD_ID}')

and now it's running through the successfully.

![Screenshot_2020-03-09 localhost 9009 mariadb suitecrm_analytics_dwh_4 phpMyAdmin 4 8 5](https://user-images.githubusercontent.com/4041275/76209672-58ef0880-61fa-11ea-8f24-4602de2e9194.png)

**Comment by samus-aran** [comment]
Just checking a few of the records and you would know better than I would if looks right :)

1. 
![Screenshot_2020-03-09 localhost 9009 mariadb suitecrm_analytics_dwh_4 F_LEAD_TRACKING phpMyAdmin 4 8 5](https://user-images.githubusercontent.com/4041275/76210719-93f23b80-61fc-11ea-9f37-c0e212033c45.png)
So this is the F_LEAD_TRACKING
and this is the change log .. 
![Screenshot_2020-03-09_changelog](https://user-images.githubusercontent.com/4041275/76210763-ad938300-61fc-11ea-9b03-2343701cd851.png)
and this is the audit logs
![Screenshot_2020-03-09 audit fields](https://user-images.githubusercontent.com/4041275/76210993-2c88bb80-61fd-11ea-94bd-a0618be8b67e.png)

**Comment by harrisward** [comment]
F_LEAD_TRACKING is not being populated. Possibly related to the point Ashley made about the additional SQL clause: AND (parent_id = '${LEAD_ID}' OR 1 = '${LEAD_ID}')

This is usually used for debugging. Need to fix this

**Comment by harrisward** [comment]
Set the LEAD_ID variable to default to 1 in the transformation which by design will bring in all available records from the staging tables

**Comment by harrisward** [comment]
Tested and working
