### ISSUE TITLE
Demo Date D_Users 'username'

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-data-integration#144]
Change the demo data so the 'username' is first and last night all lower cases with no spaces.

Currently 'USER_NAME' is the same as 'USER_FULL_NAME' i.e John Doe  - make this johndoe

**Comment by fraserward** [comment]
populateUserDimension transformation in the demo data updated.  'username' now correct.

**Comment by harrisward** [comment]
Tested
