### ISSUE TITLE
Add automatic documentation packaging script

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#149]
Add the same documentation packing functionality that was added to SuiteCRM Analytics. Refer to this ticket:

https://github.com/ivylabs/suitecrm-analytics/issues/184

**Comment by harrisward** [comment]
Pull Request: https://github.com/ivylabs/suitecrm-data-integration/pull/150

**Comment by fraserward** [comment]
Tested.  Working.
