### ISSUE TITLE
Create Opportunity Tracking Fact Table and ETL

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#15]

**Comment by samus-aran** [comment]
Just doing quick checks on opportunity audits. Similar to the Leads can you have a quick check  if they make sense.

1. OPPORTUNITY_TRACKING table
![Screenshot_2020-03-09 localhost opportunity_tracking](https://user-images.githubusercontent.com/4041275/76212161-c5203b00-61ff-11ea-8fbb-17797313eedc.png)

2. AUDIT LOGS of opprtunities SuiteCRM
![Screenshot_2020-03-09 audit_logs_opportunity](https://user-images.githubusercontent.com/4041275/76212114-a621a900-61ff-11ea-9033-79aeefe667b6.png)

3. Change Log of Opportunity SuiteCRM
![Screenshot_2020-03-09 change_log_opportunity](https://user-images.githubusercontent.com/4041275/76212100-a1f58b80-61ff-11ea-9427-17c74ebb6ebb.png)

**Comment by fraserward** [comment]
Tested
