### ISSUE TITLE
Remove row from data export parameter mapping

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#154]
**Is your feature request related to a problem? Please describe.**
We don't need this mapping for the case export anymore

**Describe the solution you'd like**
Remove this from the DLL that inserts the record into the table

This ticket is required to complete the following ticket: https://github.com/ivylabs/suitecrm-analytics/issues/201

**Comment by fraserward** [comment]
DDL updated

**Comment by harrisward** [comment]
Tested
