### ISSUE TITLE
1.4 Documentation

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#173]
Update documentation for 1.4 release

**Comment by harrisward** [comment]
Check Timezone support documentation

**Comment by rmcentee2020** [comment]
Good afternoon @harrisward,

We have now made some minor amendments to the 'Configuring Timezone' section.

Thanks,

**Comment by harrisward** [comment]
Thanks @rmcentee2020 . All the changes have been confirmed
