### ISSUE TITLE
Demo Data - Set default value for SALE_LINE_DELETED

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#174]
**Describe the bug**
In the demo data the SALE_LINE_DELETED / INVOICE_LINE_DELETED field in F_SALES and F_INVOICE_MANAGEMENT is null. It has to be set to 0 for all records in both fact tables

**Comment by fraserward** [comment]
Updated CSV's and transformations

Pull Request:  https://github.com/ivylabs/suitecrm-data-integration/pull/175

**Comment by harrisward** [comment]
Looks good
