### ISSUE TITLE
Set Adhoc Service line Items to a Quantity of 1 by default

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#176]
Adhoc Service line item quantities are set to 0 in the source system. We should set this to 1 instead. It is also used as a multiplier to calculate the discount of the service line item

**Comment by harrisward** [comment]
@johnM2401 I've made the changes in the ETL for both the F_SALES and F_INVOICE_MANAGEMENT tables which are based off sales data in SuiteCRM. Can you test the branch below?

**Comment by harrisward** [comment]
Feature Branch: https://github.com/ivylabs/suitecrm-data-integration/tree/feature-176
Pull Request: https://github.com/ivylabs/suitecrm-data-integration/pull/177

**Comment by johnM2401** [comment]
Hey @harrisward 

Looks good to me, both Sales Reports seem to be reporting correct Service Line Quantity/Discount

 Can be merged to master!
