### ISSUE TITLE
F_INVOICE_MANAGEMENT - Table appears to no longer populate with the ./run script

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-data-integration#178]
**Describe the bug**
When running the ./run script, it appears that the F_INVOICE_MANAGEMENT table no longer populates.

The other F_XXXXX tables appear to populate fine, even F_SALES, which uses Invoice data.

Additionally, the F_INVOICE_MANAGEMENT table appears to populate when Demo Data is used.

<br>

After a little bit of investigation, if I reset the Master branch back to Jun 23, (commit: 7d04ba19c4246d89b2ef898c54c247b8eab3d821 )
Then the Table appears to populate correctly.

So, it appears it may be something in the latest two commits that have caused this issue.

<br>

**Solution File
F_INVOICE_MANAGEMENT

<br>

**To Reproduce**
1. Create valid Invoice Data in the CRM
2. Run ./run script
3. Check D_INVOICES , F_SALES and F_INVOICE_MANAGEMENT, all of which should contain data
**Expected behavior**

<br>

**Screenshots**

F_SALES:
![image](https://user-images.githubusercontent.com/13675281/123639736-6594d700-d818-11eb-950a-d383237b825e.png)

F_INVOICE_MANAGEMENT:
![image](https://user-images.githubusercontent.com/13675281/123639765-6c234e80-d818-11eb-98e8-0be08667511f.png)

D_INVOICES:
![image](https://user-images.githubusercontent.com/13675281/123639796-70e80280-d818-11eb-9f9b-e7b5cd221b4c.png)

**Comment by harrisward** [comment]
Hi @johnM2401 . Good catch. Small error in the ETL. I think we need to consider creating some unit testing to catch these silly issues! Our bad.

Can you test master please?

**Comment by johnM2401** [comment]
Hey, @harrisward 

Looks good, F_INVOICE_MANAGEMENT now populating!
