### ISSUE TITLE
Invoice Due Date not updating on deleted records

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-data-integration#179]
**Describe the bug**
Invoice Due Date does not update on deleted line items records that are associated with non-deleted line item records which can produce incorrect due dates on the invoice report.

See https://github.com/ivylabs/suitecrm-data-integration/issues/138

**Solution File
F_INVOICE_MANAGEMENT

**To Reproduce**
LOAD INVOICE REPORTS
Create Invoice with 2 line items.
Run ETL
Delete 1 line item
Run ETL
update the due date on that invoice
Rn ETL

**Expected behavior**
The due date to be updated

Update the 'adjustInvoiceManagementFact' transformation to bring in 'invoice due date' field and pair them to not deleted line transaction 'due date' fields as was done on ticket ... https://github.com/ivylabs/suitecrm-data-integration/issues/138  for 'invoice date' fields.

**Comment by fraserward** [comment]
Updated transformation to include 'invoice due dates' into the update process

Pull Request:  https://github.com/ivylabs/suitecrm-data-integration/pull/180

**Comment by harrisward** [comment]
Solution looks great.

**Comment by harrisward** [comment]
Can you test again please @johnM2401 using branch https://github.com/ivylabs/suitecrm-data-integration/tree/feature-179

**Comment by johnM2401** [comment]
Hey @harrisward 
Looks good, both "Due Date" and "Invoice Date" appear to be updating now, when non-deleted line items exist.
