### ISSUE TITLE
Cleanup populateCampaignsDimensions

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-data-integration#25]
Combine the 'Drop' & 'Rename' steps into on Select Step called 'Drop / Rename'

**Comment by fraserward** [comment]
Review all populate dimension for this issue

**Comment by fraserward** [comment]
populateProductsDimesion needs a rename on table input from S_CASES to S_PRODUCTS

**Comment by harrisward** [comment]
Reviewed
