### ISSUE TITLE
Additional D_DATE Fields

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#26]
We are missing some useful date fields in the D_DATE dimension that would be useful for chart grouping. For example, YYYY-QQ.

Review this table and add the required date fields. Alter the D_DATE DDL also

**Comment by fraserward** [comment]
YYYY-QQ (2020-01)
YYYY-QQQ (2020 Q1)
YYYY-QQQQ (2020 QTR 1)
YYYY-QQQ-MM(2020 Q1 03)
YYYY-QQQ-MM-DD(2020 Q2 05 20)
YYYY-QQQQ-MMM(2020 QTR 3 Aug)
YYYY-QQQQ-MMMM(2020 QTR 1 February)

**Comment by harrisward** [comment]
Looks good
