### ISSUE TITLE
Investigate INVOICE AGE fact on F_INVOICE_MANAGEMENT

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#31]
INVOICE AGE is only calculated at ETL fact load time. This logic is likely flawed due to the INVOICE AGE never getting updated beyond the first time the fact is loaded into the DWH.

It might be an idea to create some additional ETL that updates INVOICE AGE values on a daily basis

**Comment by harrisward** [comment]
Removed INVOICE_AGE_DAYS and INVOICE_OVERDUE_DAYS from the F_INVOICE_MANAGEMENT fact table and ETL. Also removed from the DDL

**Comment by fraserward** [comment]
Checked!
