### ISSUE TITLE
Create F_SALES Fact Table

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#58]
Design and develop F_SALES fact table to support sales analysis operations

**Comment by fraserward** [comment]
Added...

DWH/FACTS/populateSalesFact.ktr
DWH/FACTS/checkModifiedSalesFact.ktr
setup/DDL/F_SALES.sql

New transformations not added to job. 
Need to have QA and possible work on checkModifiedSalesFact.ktr

**Comment by fraserward** [comment]
Need to update DDL to drop table / Default NULL / keys
