### ISSUE TITLE
Create F_CAMPAIGN_MANAGEMENT Fact Table

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#59]
Create a simple campaign management fact table to track the costs / budgets and dates of the campaign

**Comment by harrisward** [comment]
Need to define the structure of the fact table first

**Comment by harrisward** [comment]
Design added to confluence

https://ivy-is.atlassian.net/wiki/spaces/CRM/pages/1412857867/F+CAMPAIGN+MANAGEMENT

**Comment by fraserward** [comment]
Added:

DWH/FACTS/populateCampaignManagementFact.ktr
setup/DDL/F_CAMPAIGN_MANAGEMENT.sql

Not added above to job file.  QA required.  

EMail added onto suitecrm to further test

Start/Stop dates?

**Comment by fraserward** [comment]
Updates and check required.  Check DDL, & transformation.  Also placed in job
