### ISSUE TITLE
Replace 0 Dimension Keys with Text

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#6]
Dimension keys with a value of 0 have null text references. We need to replace this with "Not Set" so that filters in reports work correctly for facts that are not associated with a valid dimension key

**Comment by samus-aran** [comment]
This appears to be working, I see tables being generated with Not Sets
Testing on branch 1.1

**Comment by samus-aran** [comment]
Same again. Appears to be working still for 1.1

**Comment by harrisward** [comment]
Tested and fixed
