### ISSUE TITLE
Update Campaign Dimension in Demo Data

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-data-integration#75]
The Campaign Dimension in the demo data now needs to be updated to include:

START/END dates
Budgets
Revenue
Costs
etc

**Comment by harrisward** [comment]
I think this should be a change to the F_CAMPAIGN_MANAGEMENT fact table instead as measures and dates live in fact tables. Refer to #78

This ticket might be a misleading duplicate
