### ISSUE TITLE
Set default values for DIMENSION DEMO DATA

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#77]
The D_LEADS dimension has many null values. We need to set these values to either N/A or Not Set etc depending on the field data. We should do some anlysis on this dimension and document the dimension layout design in confluence before making the changes

**Comment by fraserward** [comment]
Update PRIMING scripts - edit default values

**Comment by fraserward** [comment]
Additional - Update populateUserDimension in DWH to set default value for USER_FULL_NAME to 'Not Set'
