### ISSUE TITLE
Drop / Truncate F_SALES fact table on reinstall

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#89]
Ross has reported that when rerunning the install o override an initial demo data install the F_SALES fact table isn't recreated empty.

**Comment by fraserward** [comment]
This is correct.  The Table F_SALES is either not dropped or truncated when running the script for a live version after using demo date.  On investigated this is also the same for F_CAMPAIGN_MANAGEMENT table.

**Comment by fraserward** [comment]
Added F_SALES & F_CAMPAIGN_MANAGEMENT to Truncate Table step of Pre-Execution job.

**Comment by fraserward** [comment]
PULL REQUEST https://github.com/ivylabs/suitecrm-data-integration/pull/91
FEATURE REQUEST https://github.com/ivylabs/suitecrm-data-integration/tree/feature-89

**Comment by harrisward** [comment]
Test and works
