### ISSUE TITLE
Create a MileageLogger example

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#9]
Create a sample that uses SuiteCRM DI custom transformation to pull data from the custom SuiteCRM plugin called MileageLogger

**Comment by samus-aran** [comment]
Hey Harris, how would I test this?

**Comment by harrisward** [comment]
Deployed a Vanilla copy of SuiteCRM. Installed the SuiteCRM Mileage Logger Module. Installed SuiteCRM Data Integration. Installed the SuiteCRM Data Integration Mileage Logger Module. Ran the ETL and checked the DWH results. All good
