### ISSUE TITLE
Investigate Demo Data

### ISSUE THREAD

**Issue by harrisward** [ivylabs/suitecrm-data-integration#90]
I suspect the demo data is populating the F_INVOICE_MANAGEMENT table with percentage and currency values for the INVOICE_LINE_DISCOUNT_VALUE column. We need to check if this is how live data also populates this column.

I think the demo data is incorrect and should only populate this field with currency values

**Comment by fraserward** [comment]
The live data populates the INVOICE_LINE_DISCOUNT_VALUE in the same way as the Demo Data.  The value in this column can be either a percentage or a amount.

The column INVOICE _LINE_DISCOUNT_AMOUNT is a calculated column taking the percentage or amount from the INVOICE_LINE_DISCOUNT_VALUE column and converting this into a monetary value.

Going forward for the purpose of Invoice Reports and such the better column to use would be the INVOICE_VALUE_DISCOUNT_AMOUNT

**Comment by fraserward** [comment]
Investigation complete
