### ISSUE TITLE
Change Invoice Discount Demo data to line up with live Data

### ISSUE THREAD

**Issue by fraserward** [ivylabs/suitecrm-data-integration#93]
The Demo data discount amounts are show as positive numbers.  The Live data brings in the same discount values as negative numbers.

The calculations for both are correct, though this results in the reports for invoices to look different as discounts are show as positive or negative depending on the data source.

Update the Demo data ETL (to show negative numbers on discount) to align value structure on the invoice reports.

**Comment by fraserward** [comment]
Updated Invoice Management Fact for the demo data with negative discount values to align with the live data

**Comment by harrisward** [comment]
Looks good
